# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/budget_cli',
                'doc_host': 'https://kervinlow.github.io',
                'git_url': 'https://github.com/kervinlow/budget_cli',
                'lib_path': 'budget_cli'},
  'syms': {'budget_cli.budget': {'budget_cli.budget.main': ('budget.html#main', 'budget_cli/budget.py')}}}
